[build]
  publish = "."
  command = "# no build command"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[template.environment]
  SUPABASE_URL = "Supabase project URL"
  SUPABASE_ANON_KEY = "Supabase anonymous key"

# HTML 파일 캐싱 방지 설정
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# index.html에 대한 추가 캐싱 방지
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# SPA 라우팅을 위한 리다이렉트
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200